### PR TITLE
Teach logging handler how to be able to send data different endpoints and ports

### PR DESCRIPTION
**Pull request by eflanagan-r7**

### CODE REVIEW

**Comment by eflanagan-r7** [comment]
@vilda @jcftang

**Comment by vilda** [comment]
:+1:

**Comment by eflanagan-r7** [comment]
-1 Unfortunately it doesn't seem to be working with "df.logentries.net" endpoint which is the whole point of this PR

**Comment by eflanagan-r7** [comment]
Got the right address to send to now. Should be ok to merge

**Pull request merged**
