### PR TITLE
Avoid using lock in emit

### PR DESCRIPTION
**Pull request by graingert**
This is #34 rebased

### CODE REVIEW

**Comment by graingert** [comment]
@StephenHynes7 bump

**Comment by graingert** [comment]
@StephenHynes7 bump

**Comment by jcftang** [comment]
@graingert what's the rationale behind removing the lock?

**Comment by graingert** [comment]
it makes emit slow, eg there's no point in using a queue when you wrap emit with a big lock

**Comment by jcftang** [comment]
Okay, that makes sense if the queue doesn't fill up, I think removing the lock might cause issues if the queue fills up. It might also be a good idea to check if the queue is full or not and act accordingly when it is full.

**Comment by graingert** [comment]
Python queues don't fill up, they automatically extend as you use them

**Comment by jcftang** [comment]
See, https://github.com/graingert/le_python/blob/avoid-using-lock-in-LE/logentries/helpers.py#L34 and https://github.com/graingert/le_python/blob/avoid-using-lock-in-LE/logentries/utils.py#L47, The queue appears to be intialised with a fixed upper bound in this case. The thread will block in this case, I guess the behaviour should be agreed on when the queue gets full to avoid messages being dropped.

**Comment by graingert** [comment]
@jcftang this lock was only added to stop the thread being started more than once in:

https://github.com/logentries/le_python/pull/38/files#diff-0d684a53d5b031bb45bbedf8d39a9250R184

It's nothing to do with the queue filling up

**Pull request merged**
