### PR TITLE
Avoiding Queue.Full in logger emit method

### PR DESCRIPTION
**Pull request by vilda**
When internal queue is full, any attempts to push more messages should not affect logging thread

### CODE REVIEW

**Comment by vilda** [comment]
Can you check this @MarkLC-r7 @jtheuer ?

**Comment by jtheuer** [comment]
I think this approach makes sense. Thanks for fixing.

**Comment by MarkLC-r7** [comment]
+1

**Comment by luizgois-luizalabs** [comment]
Unable to configure handler 'logentries_handler': Cannot resolve 'logentries.LogentriesHandler': No module named 'Queue'

**Pull request merged**
