### PR TITLE
don't raise if thread already started

### PR DESCRIPTION
**Pull request by drgarcia1986**
to prevent `threads can only be started once`

same of #9

### CODE REVIEW

**Comment by jairhenrique** [comment]
:+1:

**Comment by drgarcia1986** [comment]
@StephenHynes7 you can review?

**Comment by sivabudh** [comment]
How come this is not merged yet? Wow.

**Comment by drgarcia1986** [comment]
My projects with aiohttp only works with this patch :cry:

**Comment by drgarcia1986** [comment]
I'm need to rebase with #53 to working in my projects

**Comment by vilda** [comment]
Thanks @drgarcia1986

**Pull request merged**
